### PR TITLE
Add an anonymous read-only JSON REST API

### PR DESCRIPTION
**Pull request by jamestmartin**
This API does not require login and does not allow performing any sort of modifications.
It is intended to be used both by dad.zone and the hypothetical DAD 3.0.

Here's why these changes are necessary:

* The comments, challenges, and submissions endpoints are intended to be used when linking to them from a post (e.g. `>>C139`).
* The challenges and submissions endpoints are intended to be used when creating a thread about them (e.g. a challenge discussion thread or critique request thread)
* The users endpoints are intended to be used frequently because each post is associated with a user.
* This amounts to adding API endpoints for a substantial portion of the data that can be accessed anonymously, which is good prep for the distant DAD 3.0.

More description of the actual changes made below.

This WIP PR is based on the existing work in the cross-site authentication PR, #104; in particular, it depends on the support for CORS.

### CODE REVIEW

**Comment by jamestmartin** [comment]
I've additionally fixed a security bug with the participation system. Basically, `GET` requests are assumed not to do anything but return the resource, so browsers have no problem fetching them automatically. However, in the case of participations, joining and leaving challenges was based on a query parameter to `:show`, which is ` GET` request.

The attack would be trivial: just link people to a page with a bunch of `` tags (or something similar) and their browsers would automatically register/unregister them from all of those challenges.

It's not all that important, but it's worth mentioning and explaining so that you don't make that kind of mistake again!

**Comment by jamestmartin** [comment]
I ended up adding these new endpoints:

* `GET /users/:user_id/awards`
* `GET /users/:user_id/awards/:badge_id`
* `GET /comments/:id`
* `GET /challenges/:challenge_id/participations`
* `GET /challenges/:challenge_id/participations/:user_id`
* `POST /challenges/:challenge_id/participations`
* `DELETE /challenges/:challenge_id/participations/:user_id`

And adding JSON to these:
* `GET /challenges`
* `GET /challenges/:id`
* `GET /challenges/:id/entries`
* `GET /submissions/:id`
* `GET /users/:id`
* `GET /users/:id/submissions`

I ended up adding more than strictly necessary for the task at hand, but the result was a *complete* API for the endpoints I added. In the process I figured out exactly how I want the dadzone API to work, got a bunch more insight into how to write good Rails code, and gave us a head start for DAD 3.0.

All I should have to do before this is ready to merge is testing. Writing tests for all of this sounds... really tedious, tbh. I don't think it's worth it in this case, because it's all read-only and unauthenticated, so there's not much to test.

I also wrote a bunch of `FIXME`s, but those mostly have to do with the model which right now is, fortunately, not my problem ;)

**Comment by jamestmartin** [comment]
If you're wondering what `_links` and `_embedded` mean and why some properties use them and not others: it's hard and time-consuming to explain, so I'm not going to give a specific description ([there's a spec](https://tools.ietf.org/html/draft-kelly-json-hal-00), but it's not enough to understand what's going on on its own). So instead, I'll just quickly describe the *benefits* of that design:

* The API producer can freely choose (or allow the consumer to choose) whether to embed data directly in a response or to simply tell the API consumer how to access that data, which provides a lot of flexibility and potential performance benefits. For example, when returning a request for information about a user, it can provide information about that user's submissions in three ways:
  1. Link to the user's submissions list. The API consumer knows how to see the user's submissions, but doesn't know anything about them just yet.
  2. List links to the user's submissions. The API consumer knows which submissions belong to the user, but has to look them up individually for more information.
  3. List the user's submissions embedded. The API consumer has all of the information about all of the user's submissions right there.
* The API consumer can lazily (lazy as in functional programming) load data. You can write your code as if you already have all of the data available to you, and your model will automatically retrieve it as necessary. This is possible for normal APIs too, but this allows it to be done in a generic way (because how to navigate the data is part of the data).
* The API consumer doesn't have to duplicate the producer's routing code, which makes the API easier to use, and allows the producer to change the way it routes things without requiring changes to consumer code.

Blessed hypertext APIs. I'm looking forward to working with you more.

The DAD zone API will behave exactly the same way, and I intend to use cross-domain (gasp) linked resources, which is gonna be great because it means I won't have to put in any extra effort to allow intermixing the APIs, which is something extremely tedious that I'd have to do if I were doing server-side rendering.

**Comment by jamestmartin** [comment]
I need to add some index stuff for nsix's benefit (plus just because it'd be satisfying to have a 100% complete API for anonymous read-only stuff, assuming I didn't forget anything), and do some quick re-testing to make sure I didn't break anything while rebasing (because there were a few weird changes done that could affect this code).

That said, even if it's not technically *quite* merge-ready, you're still welcome to review it, and it'll probably be merge-ready again tonight.

**Comment by nsixcantcode** [comment]
One request: I need to be able to loop over each user on the site and get their submission history. To do that I need to know when I can stop looping over users. Would it be possible to add an endpoint that returns the max user id or maybe an array of existing user ids?

**Comment by jamestmartin** [comment]
@nsixcantcode Added a `max_id` field to `/users.json`.

You can also use `_links.next` which may be used for paging through the users list (`/users.json`). `next` will not be set if there are no more users to list (although you will end up with exactly one empty page before then).

**Comment by jamestmartin** [comment]
Marking as draft *again* because re-opening registrations broke tons of shit... sigh...

The preliminary merge is done but the API doesn't deal with soft deletes at all. Also, the way banana handled soft deletes is ugly and probably something I'll want to clean up.

**Comment by jamestmartin** [comment]
I think I'm gonna be okay with a bunch of merges from master because this entire PR is gonna end up squashed anyway, and the merges involve actual breaking changes, so using rebase wouldn't be a good idea.

**Pull request closed without merging**
